### ISSUE TITLE
[feature request] add API for manipulate json object

### ISSUE THREAD

**Issue by lwyj123** [kaelzhang/node-comment-json#11]
It will be good If there are some APIs like [Mongo: Update Document](https://docs.mongodb.com/manual/tutorial/update-documents/) or [immutability-helper](https://github.com/kolodny/immutability-helper) to modify the contents of the JSON.

**Comment by kaelzhang** [comment]
There is already a method called `assign`, what additional APIs do you want?

```js
const {
  assign
} = require('comment-json')
```

Could you provide your use case?

**Comment by lwyj123** [comment]
manipulate the JSON, like this picture

![image](https://user-images.githubusercontent.com/9214496/65847405-002a6280-e374-11e9-82df-34a0c4211496.png)

**Comment by kaelzhang** [comment]
Why we need this? `db.collection.update` is completely another story.

Unlike mongo documents, JSON objects are pure objects without abstractions and meta info.

**Comment by lwyj123** [comment]
I write a package for update object(support comment-json) using declaration way. [sundogrd/declaration-update](https://github.com/sundogrd/declaration-update). close it.
