### ISSUE TITLE
[feature request] Preserve duplicate keys

### ISSUE THREAD

**Issue by forivall** [kaelzhang/node-comment-json#13]
**Why this feature is better to be included in comment-json? Please describe the scenario**
A common pattern to create comments that can be parsed by `JSON.parse` is the following:
```
{
  "name": "foo",
  "//": "this is a comment",
  "//": "this is another comment"
}
```
As these are duplicate keys, they will be lost in a parse/stringify cycle. It would be nice if they could be preserved.

**Are you willing to submit a pull request to implement this rule?**
Maybe? It's not an urgent thing for me, so it wouldn't be any time soon.

**Comment by kaelzhang** [comment]
Why you need this kind of JSON structure? JSON is a HashMap, and should not contains duplicate keys.

What result do you expect the example to be parsed into?

****
With comment-json, you could just parse

```js
{
  "name": "foo",
  // this is a comment
  // this is another comment
}
```
and preserve comments

**Comment by forivall** [comment]
Yes, i understand all of those things. The way that JSON is parsed is such that the last defined duplicate entry is what is kept in the object. So, i would expect all previous instances of that key to be in the `CommentArray` as comment entries, as a separate comment type of `DuplicateKey` or something like that.

In particular, i would use this in circumstances where I'm modifying a JSON file that will be consumed by other tools that can't handle comments in JSON. For these files, duplicate-key based comments are ideal, as it allows the file to still be parsed.

For example, here's someone using this trick, with empty string keys: https://gist.github.com/MoOx/5271067

**Comment by kaelzhang** [comment]
`comment-json` is **NOT** a JSON editor to manipulate a JSON file which will be used by a standard JSON parser, while it is to edit a non-standard JSON file with `//` and `/* */` comments

**Comment by forivall** [comment]
Is it just out of scope, or is there some intrinsic problem here? ie. why not? It's a valid use case that I have.

**Comment by kaelzhang** [comment]
The reason why people need duplicate keys is that JSON doesn't support comments and people use `'//'` as object key to store comment text.

```json
{
  "//": "comment for foo",
  "foo": "bar"
}
```
But if we could parse JSON with comments, and we will not need duplicate keys.

Besides, duplicate keys brings logical contradictions.

Let's suppose that JSON supports duplicate keys, and how can distinguish each parsed object of the following JSON strings?

1.
```js
{
  "//": "foo",
  "//": "bar"
}
```

2.
```js
{
  "//": [
    "foo",
    "bar"
  ]
}
```

And in the mean time, it is better that the parsed object shall be stringified into a equivalent JSON string of the original one by both `commentJSONStringifier` and the vanilla `JSON.stringify`.

**Comment by forivall** [comment]
I still don't see how your statements support your conclusion, but it did lead me to a logical case that would make supporting duplicate keys prohibitive (at least, within your project):

My proposed structure for `// what should object be?` in your above example would be:
```
{
  foo: 'baz',
  [Symbol(before:foo)]: [ { type: 'DuplicateKey', key: "foo", value: "bar" } ]
}
```

(also, `console.log(JSON.stringify(object) === JSON.stringify(JSON.parse(str)))` will always return false because of object equality, but that's not the point)

However, the problem would be if you changed the order of keys in your object. For example:
```
const str = `
{
  "foo": "bar",
  "bar": "biz",
  "foo": "baz"
}
`
const obj = myJSONParser(str)
```

Here, obj would be 
```
{
  bar: 'biz',
  [Symbol(before:bar)]: [ { type: 'DuplicateKey', key: "foo", value: "bar" } ],
  foo: 'baz'
}
```
If we were to rearrange the iteration order of the keys in an operation like:
```
const { bar, ...o2 } = obj;
console.log(myJSONStringify({ ...o2, bar }))
```
it would result with
```
{
  "foo": "baz",
  "foo": "bar",
  "bar": "biz"
}
```
in which, we have now clobbered the actual final value of `"foo"`.
