### ISSUE TITLE
[Typescript] Typescript type definition need to be updated for 'assign'

### ISSUE THREAD

**Issue by lwyj123** [kaelzhang/node-comment-json#14]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/comment-json

for 'assign' method

**Comment by kaelzhang** [comment]
DefinitelyTyped is not maintained by me.

Maybe I could add a index.d.ts to the package of comment-json

**Comment by kaelzhang** [comment]
Blocked by microsoft/TypeScript#1863 which has been opened for **FIVE** years

Can't imagine that ts does not support symbols as object keys.

**Comment by kaelzhang** [comment]
Only `any` can rescue typescript. 

Just published `2.4.1`

**Comment by kaelzhang** [comment]
Im gonna close this. Be free to reopen this issue if the issue exists
