### ISSUE TITLE
CommentArray.splice should shift same-line comments

### ISSUE THREAD

**Issue by wnayes** [kaelzhang/node-comment-json#16]
There is this comment in the splice implementation:

        // If no element removed, just skip moving comments.

However, consider the following input:

```
{
    AnArray: [
        { one: 1 },
        { two: 2 }, 
        { four: 4 }, // Comment about four
    ]
}
```

If I `AnArray.splice(2, 0, { three: 3 })`, the "Comment about four" will now be associated with the inserted line.

I get the unexpected output when stringifying:
```
{
    AnArray: [
        { one: 1 },
        { two: 2 },
        { three: 3 }, // Comment about four
        { four: 4 },
    ]
}
```

**What did you expect to happen?**
I expected the comments that are on the same line as an array entry to shift accordingly.

```
{
    AnArray: [
        { one: 1 },
        { two: 2 },
        { three: 3 },
        { four: 4 }, // Comment about four
    ]
}
```

**Are you willing to submit a pull request to fix this bug?** Not at this time. But thanks for the useful library!

* **Node Version:** Unknown
* **comment-json Version** 2.4.1

**Comment by kaelzhang** [comment]
Nice catch, buddy~ Landed in `2.4.2`
