### ISSUE TITLE
simple number is replaced by {}

### ISSUE THREAD

**Issue by yaitskov** [kaelzhang/node-comment-json#22]
**Tell us about your environment**
Firefox 
* **Node Version:**

node --version
v14.0.0

* **comment-json Version**
3.0.2

**Please show your use case / code slices / code link that could reproduce the issue**

```js

commentJson.stringify(commentJson.parse("333 /* ddd */"), null, 2)


```

**What did you expect to happen?**

I expected to get
```
"333 /* ddd */"
```
but 
```
"{} /* ddd */"
```
**Are you willing to submit a pull request to fix this bug?**

**Comment by kaelzhang** [comment]
Landed in `3.0.3`
