### ISSUE TITLE
Support single quote strings

### ISSUE THREAD

**Issue by yaitskov** [kaelzhang/node-comment-json#23]
JSON files use single quotes sometimes instead of double ones. 
It is behind the JSON standard, but
main stream Java libraries (Jackons and Gson) support such feature.
I guess this practice exists, because of convenience for manual typing.
 Single quote is easier to type than double one.
I have to support comments inside JSON document. 
When comments and single quotes are mixed in the same document I cannot parse it anyhow.
Single quote and comments are related feature - oriented for human written files.

**Comment by yaitskov** [comment]
[here it is my solution](https://github.com/kaelzhang/node-comment-json/pull/24) I am going to use in my project.

**Comment by kaelzhang** [comment]
IMO, single quote support is a non-goal of this project.

If you just need to parse a json file with comments and even other stuffs into an object, and you do not need to stringify the object back to commented json, you could use JSON5 directly.

**Comment by kaelzhang** [comment]
Gonna close this. Be free to reopen if necessary
