### ISSUE TITLE
`JSON.assign` doesn't preserve root comments

### ISSUE THREAD

**Issue by manuth** [kaelzhang/node-comment-json#26]
* **Node Version:** 12.16.1
* **comment-json Version** 4.0.2

**Please show your use case / code slices / code link that could reproduce the issue**

```ts
import JSON = require("comment-json");
import dedent = require("dedent");

JSON.stringify(
    JSON.assign(
        {},
        JSON.parse(
            dedent(
                `
                    /* hello world */
                    {
                        /* hello world */
                        "a": "b"
                    }`))),
    null,
    4);
```

**What did you expect to happen?**
Both comments should be preserved:
```jsonc
/* hello world */
{
    /* hello world */
    "a": "b"
}
```

**What did actually happen?**
The comment at the root level is removed:

```jsonc
{
    /* hello world */
    "a": "b"
}
```

**Comment by kaelzhang** [comment]
Nice catch~ Landed in `4.0.3`

**Comment by manuth** [comment]
Awesome job! Thank you very much 😄

**Comment by kaelzhang** [comment]
For more details, check here: https://github.com/kaelzhang/node-comment-json#special-cases-about-keys

Sorry that it is recommended to upgrade to `4.0.4` coz I missed a case.
