### ISSUE TITLE
Esprima 2.7.0 breaks comment-json

### ISSUE THREAD

**Issue by ozzx62** [kaelzhang/node-comment-json#4]
Reproduce:
1. Clean up node_modules folder.
2. npm install
3. npm test

138 passing (114ms)
9 failing

Don't know the root cause yet, but this is affecting my builds.

A temporary fix would be adding 
"esprima": "2.6.0"
to the dependencies.

**Comment by kaelzhang** [comment]
Thanks for the notice!

Esprima 2.7.0 changes the return value of `esprima.tokenize`, see jquery/esprima#1351.

Please removes node_modules, and npm install again.
