### ISSUE TITLE
npm reports only DefinitelyTyped types

### ISSUE THREAD

**Issue by karlhorky** [kaelzhang/node-comment-json#43]
First of all, thanks for `comment-json`, looks very useful!

**Tell us about your environment**

* **Node Version:** n/a
* **comment-json Version:** 4.2.3

**Please show your use case / code slices / code link that could reproduce the issue**

On [the npm page for `comment-json`](https://www.npmjs.com/package/comment-json), there is a "DT" symbol, indicating that the library has 3rd-party [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) types:

![Screenshot 2024-06-20 at 09 57 52](https://github.com/kaelzhang/node-comment-json/assets/1935696/d6a68df5-0def-4d5a-87bb-74ea4217df47)

The "DT" symbol links to [`@types/comment-json`](https://www.npmjs.com/package/@types/comment-json), which has a deprecation notice:

```
This is a stub types definition. comment-json provides its own type definitions, so you do not need this installed.
```

![Screenshot 2024-06-20 at 10 02 17](https://github.com/kaelzhang/node-comment-json/assets/1935696/ef2c314f-7551-4fc4-bccb-d79532c57fb6)

Reading through [the Install docs in the readme](https://github.com/kaelzhang/node-comment-json#install), there is also a notice that there is already types included:

> # Install
>
> ```bash
> $ npm i comment-json
> ```
>
> ~For TypeScript developers, [@types/comment-json](https://www.npmjs.com/package/@types/comment-json) could be used~
> 
> Since `2.4.1`, `comment-json` contains typescript declarations, so you might as well remove `@types/comment-json`.

This is confusing and hidden though, and should be reported properly at the top of the page on npm.

**What did you expect to happen?**

npm should report that types are available in the library, with the blue "TS" symbol as can be seen on [the npm page for `jest`](https://www.npmjs.com/package/jest):

![Screenshot 2024-06-20 at 09 58 00](https://github.com/kaelzhang/node-comment-json/assets/1935696/9f27ccc0-6f95-4409-99cc-64cade91d0a0)

The `jest` package includes its own types and the npm page shows the "TS" symbol, even though the package [`@types/jest`](https://www.npmjs.com/package/@types/jest) also exists.

**Are you willing to submit a pull request to fix this bug?**

Maybe, if it's fast. However, I'm not sure what exactly to fix - maybe it's something in `package.json`... 🤔

**Comment by kaelzhang** [comment]
Just remove `@types/comment-json` from your dependencies.

I don't think it is an issue of this package.

**Comment by karlhorky** [comment]
I think it's indeed a problem of the package.

In my analysis of [the `comment-json` `package.json` file](https://unpkg.com/browse/comment-json@4.2.4/package.json), there is no [`"types"` field in `package.json`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package):

```json
{
  "name": "comment-json",
  "version": "4.2.4",
  "description": "Parse and stringify JSON with comments. It will retain comments even after saved!",
  "main": "src/index.js",
  "scripts": {
    "test": "npm run test:only",
    "test:only": "npm run test:ts && npm run test:node",
    "test:ts": "tsc -b test/ts/tsconfig.build.json && node test/ts/test-ts.js",
    "test:node": "NODE_DEBUG=comment-json nyc ava --timeout=10s --verbose",
    "test:dev": "npm run test:only && npm run report:dev",
    "lint": "eslint .",
    "fix": "eslint . --fix",
    "posttest": "npm run report",
    "report": "nyc report --reporter=text-lcov > coverage.lcov && codecov",
    "report:dev": "nyc report --reporter=html && npm run report:open",
    "report:open": "open coverage/index.html"
  },
  "files": [
    "src/",
    "index.d.ts"
  ],
  "repository": {
    "type": "git",
    "url": "git://github.com/kaelzhang/node-comment-json.git"
  },
  "keywords": [
    "comment-json",
    "comments",
    "annotations",
    "json",
    "json-stringify",
    "json-parse",
    "parser",
    "comments-json",
    "json-comments"
  ],
  "engines": {
    "node": ">= 6"
  },
  "ava": {
    "files": [
      "test/*.test.js"
    ]
  },
  "author": "kaelzhang",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/kaelzhang/node-comment-json/issues"
  },
  "devDependencies": {
    "@ostai/eslint-config": "^3.6.0",
    "ava": "^4.0.1",
    "codecov": "^3.8.2",
    "eslint": "^8.8.0",
    "eslint-plugin-import": "^2.25.4",
    "nyc": "^15.1.0",
    "test-fixture": "^2.4.1",
    "typescript": "^4.5.5"
  },
  "dependencies": {
    "array-timsort": "^1.0.3",
    "core-util-is": "^1.0.3",
    "esprima": "^4.0.1",
    "has-own-prop": "^2.0.0",
    "repeat-string": "^1.6.1"
  }
}
```

Compare that with [the `package.json` file from `jest`](https://unpkg.com/browse/jest@29.7.0/package.json), which sets `"types"` in `package.json`:

```json
{
  "name": "jest",
  "description": "Delightful JavaScript Testing.",
  "version": "29.7.0",
  "main": "./build/index.js",
  "types": "./build/index.d.ts",
  "exports": {
    ".": {
      "types": "./build/index.d.ts",
      "default": "./build/index.js"
    },
    "./package.json": "./package.json",
    "./bin/jest": "./bin/jest.js"
  },
  "dependencies": {
    "@jest/core": "^29.7.0",
    "@jest/types": "^29.6.3",
    "import-local": "^3.0.2",
    "jest-cli": "^29.7.0"
  },
  "devDependencies": {
    "@tsd/typescript": "^5.0.4",
    "tsd-lite": "^0.7.0"
  },
  "peerDependencies": {
    "node-notifier": "^8.0.1 || ^9.0.0 || ^10.0.0"
  },
  "peerDependenciesMeta": {
    "node-notifier": {
      "optional": true
    }
  },
  "bin": "./bin/jest.js",
  "engines": {
    "node": "^14.15.0 || ^16.10.0 || >=18.0.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/jestjs/jest.git",
    "directory": "packages/jest"
  },
  "homepage": "https://jestjs.io/",
  "license": "MIT",
  "keywords": [
    "ava",
    "babel",
    "coverage",
    "easy",
    "expect",
    "facebook",
    "immersive",
    "instant",
    "jasmine",
    "jest",
    "jsdom",
    "mocha",
    "mocking",
    "painless",
    "qunit",
    "runner",
    "sandboxed",
    "snapshot",
    "tap",
    "tape",
    "test",
    "testing",
    "typescript",
    "watch"
  ],
  "publishConfig": {
    "access": "public"
  },
  "gitHead": "4e56991693da7cd4c3730dc3579a1dd1403ee630"
}
```

**Comment by karlhorky** [comment]
PR open:

- https://github.com/kaelzhang/node-comment-json/pull/46

**Comment by karlhorky** [comment]
Thanks for the review and merge of PR #46 and release in `comment-json@4.2.5` 🙌

I can confirm that this solved the issue:

![Screenshot 2024-08-11 at 15 05 20](https://github.com/user-attachments/assets/cd8f7bac-0fd1-478d-9758-01fc5e465551)
