### ISSUE TITLE
what about single quotes too?

### ISSUE THREAD

**Issue by a-x-** [kaelzhang/node-comment-json#5]
ll by cool to parse json like js
```js
{
  // jsn
  foo: 'bar',
  qux: true
}
```

it's not js, its not requires expression (object in parentheses) `({ some: 'js-json' })`

**Comment by a-x-** [comment]
http://json5.org

**Comment by yaitskov** [comment]
I need single quotes too. I didn't about JSON5. Does it support comments?
If yes then what is the reason for this library to exist?

**Comment by a-x-** [comment]
@yaitskov, yeah, use json5, 
node-comment-json is useless ;)

**Comment by kaelzhang** [comment]
@a-x- @yaitskov you guys really need to read the [document](https://github.com/kaelzhang/node-comment-json#why)
